services:
  database:
    image: postgres
    ports:
      - 5011:5432
    volumes:
      - pgdata:/var/lib/postgresql
    env_file:
      - ./packages/db/.env
  queue:
    image: redis
    ports:
      - 5012:6379
volumes:
  pgdata:
